SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
-- Place the database in ARCHIVELOG mode
ALTER DATABASE ARCHIVELOG;
-- open and save pluggable database state as opened
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE orclpdb OPEN;
ALTER PLUGGABLE DATABASE orclpdb SAVE STATE;
exit